In [32]:
import numpy as np
import pandas as pd

In [33]:
arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

In [34]:
temp = np.array([[2.3, 1.4], [0.3,2.2]])
temp

array([[2.3, 1.4],
       [0.3, 2.2]])

In [35]:
c = np.array([[1,2,3],[4,5,6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
d = np.array(((1,2,3),(4,5,6)))
d

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
e = np.array([(1,2,3), [4,5,6], (9,8,7)])
e

array([[1, 2, 3],
       [4, 5, 6],
       [9, 8, 7]])

In [38]:
d = np.array(((1,2,3,7),(4,5,6,8)),dtype=float)
d

array([[1., 2., 3., 7.],
       [4., 5., 6., 8.]])

In [39]:
f = np.ones((3,3))
f

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [40]:
f = np.zeros((3,3))
f

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [41]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
np.arange(5,100,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
       90, 95])

In [43]:
np.arange(2,10,0.1).reshape(8,10)

array([[2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9],
       [3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9],
       [4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9],
       [5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9],
       [6. , 6.1, 6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9],
       [7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7, 7.8, 7.9],
       [8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9],
       [9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9]])

In [44]:
np.linspace(0,7,3)

array([0. , 3.5, 7. ])

In [45]:
np.random.random((3,3))

array([[0.8879138 , 0.33440112, 0.00831898],
       [0.69750431, 0.55124562, 0.51740749],
       [0.1196375 , 0.9351955 , 0.37132034]])

In [46]:
z = np.zeros(10)
o = np.ones(10)
arrange_1 = np.arange(10)
linspace_1 = np.linspace(0,1,5)
print("zeros :", z)
print("ones :", o)
print("arrange_1 :", arrange_1)
print("linspace_1 :", linspace_1)

zeros : [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
ones : [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
arrange_1 : [0 1 2 3 4 5 6 7 8 9]
linspace_1 : [0.   0.25 0.5  0.75 1.  ]


In [47]:
arrange_1_safe = np.where(arrange_1 == 0, 1e-10, arrange_1)
print(o+z)
print(o*arrange_1)
print(o/arrange_1)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[       inf 1.         0.5        0.33333333 0.25       0.2
 0.16666667 0.14285714 0.125      0.11111111]


/tmp/ipykernel_27544/2512165338.py:4: RuntimeWarning: divide by zero encountered in divide
  print(ones/arrange_1)


In [48]:
a = np.arange(6)
a = a[np.newaxis, : ]
a

array([[0, 1, 2, 3, 4, 5]])

In [49]:
df = pd.DataFrame({"int_col" : arrange_1, "float_col" : z, "str_col" :  ["asd", "asdd", "dsa", "wasd", "s","asdf","qwe", 'w',None, "10"]})
df

int_col  float_col str_col
0        0        0.0     asd
1        1        0.0    asdd
2        2        0.0     dsa
3        3        0.0    wasd
4        4        0.0       s
5        5        0.0    asdf
6        6        0.0     qwe
7        7        0.0       w
8        8        0.0    None
9        9        0.0      10

In [50]:
## Tasks
my_array = np.arange(5,101,5)
my_array

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100])

In [51]:
array2 = my_array[my_array%10==0]
array2

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [52]:
arr2d = array2.reshape(-1, 2)
arr2d

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

In [53]:
arr2d5 = arr2d-5
arr2d5

array([[ 5, 15],
       [25, 35],
       [45, 55],
       [65, 75],
       [85, 95]])

In [54]:
twoArrs = np.hstack((arr2d,arr2d5))
# twoArrs = twoArrs.T
twoArrs

array([[ 10,  20,   5,  15],
       [ 30,  40,  25,  35],
       [ 50,  60,  45,  55],
       [ 70,  80,  65,  75],
       [ 90, 100,  85,  95]])

In [55]:

division_result = twoArrs[1] / twoArrs[3]
division_result1 = twoArrs[2] / twoArrs[3]


In [56]:

twoArrsCopy = twoArrs.copy().astype(float)
twoArrsCopy[1] = division_result
twoArrsCopy[2] = division_result1
# twoArrsCopy = twoArrsCopy.T
print(twoArrsCopy)


[[ 10.          20.           5.          15.        ]
 [  0.42857143   0.5          0.38461538   0.46666667]
 [  0.71428571   0.75         0.69230769   0.73333333]
 [ 70.          80.          65.          75.        ]
 [ 90.         100.          85.          95.        ]]


In [57]:
# Задание 7
#Оставить только те значения, которые не изменились после деления

rows_equal = np.all(twoArrsCopy == twoArrs, axis=1)

leftover = twoArrsCopy[rows_equal]

leftover

array([[ 10.,  20.,   5.,  15.],
       [ 70.,  80.,  65.,  75.],
       [ 90., 100.,  85.,  95.]])

In [58]:
leftover[[0, 2]] = leftover[[2, 0]]
leftover

array([[ 90., 100.,  85.,  95.],
       [ 70.,  80.,  65.,  75.],
       [ 10.,  20.,   5.,  15.]])

In [59]:
#9.1.	Получить среднее, медиану и стандартное отклонение для каждой строки, используя команды np.mean(), np.median(), np.std().
mean_values = np.mean(leftover, axis=1)

median_values = np.median(leftover, axis=1)

std_values = np.std(leftover, axis=1)

print("Mean:", mean_values)
print("Median:", median_values)
print("STD:", std_values)

Mean: [92.5 72.5 12.5]
Median: [92.5 72.5 12.5]
STD: [5.59016994 5.59016994 5.59016994]


In [60]:
max_val = np.max(leftover, axis=1, keepdims=True)

normalized_result = leftover / max_val
print(max_val)
print(normalized_result)

[[100.]
 [ 80.]
 [ 20.]]
[[0.9    1.     0.85   0.95  ]
 [0.875  1.     0.8125 0.9375]
 [0.5    1.     0.25   0.75  ]]
